apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: f7w17s6r6-python 
  janus-idp.io/tekton: f7w17s6r6-python
  backstage.io/kubernetes-id: f7w17s6r6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f7w17s6r6-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml